apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress-deployment
  labels:
    app: fortress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortress
  template:
    metadata:
      labels:
        app: fortress
    spec:
      containers:
      - name: fortress
        image: 741927926526.dkr.ecr.us-west-2.amazonaws.com/fortress:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fortress-service
spec:
  type: LoadBalancer
  selector:
    app: fortress
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001